### ISSUE TITLE
go-hdb can not support for 'select something group by' ? 

### ISSUE THREAD

**Issue by lulouis** [SAP/go-hdb#22] opened 2018-06-11 10:24 UTC
Dear SAP Engineers:
There was a strange problem,like this:
we try to get data from a HANA CUB，through two ways(sql1 & sql2)，the first one can running correctly，the second one was running aborted，but those two sql-statements all are well in the HANA STUDIO.

## You can see my sql1 and sql2 in those code . 
//date format:yyyy-MM-dd
func BrandWithChannel(yourDate string)(list []_BrandWithChannel ,err error){

	// utils.HANA_DRIVER, utils.HANA_DNS ------>
	// const (
	// 	HANA_DRIVER = "hdb"
	// 	HANA_DNS    = "hdb://SYSTEM:h1231asy@192.168.2.34:30015"
	// ) <------ utils.HANA_DRIVER, utils.HANA_DNS

	conn, _ := sql.Open(utils.HANA_DRIVER, utils.HANA_DNS)
	//defer db.Close()
	if err !=nil {
		fmt.Println(err.Error())
	}

	
	var sql1 = fmt.Sprintf(`SELECT  BEHVO,BVTXT,KTOKD
		,CC_YEAR_SUM , CC_MONTH_SUM , CC_DAY_SUM ,
		CC_TBYEAR_SUM , CC_TBMONTH_SUM , CC_HBMONTH_SUM "
		from "_SYS_BIC"."MF_SALES.DAILYSALE/SALES_D_BEHVO" ('PLACEHOLDER' = ('$$IP_TO_DATE$$', '%s'))`
		, yourDate)

	var sql2 = fmt.Sprintf(`SELECT BEHVO,BVTXT,KTOKD
		,sum(CC_YEAR_SUM) AS CC_YEAR_SUM, sum(CC_MONTH_SUM) AS CC_MONTH_SUM, sum(CC_DAY_SUM) AS CC_DAY_SUM, 
		sum(CC_TBYEAR_SUM) AS CC_TBYEAR_SUM, sum(CC_TBMONTH_SUM) AS CC_TBMONTH_SUM, sum(CC_HBMONTH_SUM) AS CC_HBMONTH_SUM 
		from "_SYS_BIC"."MF_SALES.DAILYSALE/SALES_D_BEHVO" ('PLACEHOLDER' = ('$$IP_TO_DATE$$', '%s')) 
		GROUP BY BEHVO,BVTXT,KTOKD`
		, yourDate)

	fmt.Printf("my sql1：%s \r\n",sql1)
	fmt.Printf("my sql2：%s \r\n",sql2)
	rows,err := conn.Query(sql2)

	if err!=nil {
		fmt.Printf("my sql：%s \r\nwhat happened：%s",sql2,err.Error())
		return nil,err
	}

	
	for rows.Next() {
		var temp _BrandWithChannel
		var _CC_YEAR_SUM []uint8
		var _CC_MONTH_SUM []uint8
		var _CC_DAY_SUM []uint8
		var _CC_TBYEAR_SUM []uint8
		var _CC_TBMONTH_SUM []uint8
		var _CC_HBMONTH_SUM []uint8

		arr := []interface{}{
			&temp.BrandCode,&temp.BrandAlias,&temp.ChannelCode,
			&_CC_YEAR_SUM,&_CC_MONTH_SUM,&_CC_DAY_SUM, 
			&_CC_TBYEAR_SUM,&_CC_TBMONTH_SUM,&_CC_HBMONTH_SUM, 
		}

		if err = rows.Scan(arr...);err != nil {
			fmt.Printf("my sql：%s \r\nwhat happened：%s",sql2,err.Error())
			return nil, err
		} else {
			temp.CC_YEAR_SUM = utils.ToFloat64(_CC_YEAR_SUM)
			temp.CC_MONTH_SUM = utils.ToFloat64(_CC_MONTH_SUM)
			temp.CC_DAY_SUM = utils.ToFloat64(_CC_DAY_SUM)
			temp.CC_TBYEAR_SUM = utils.ToFloat64(_CC_TBYEAR_SUM)
			temp.CC_TBMONTH_SUM = utils.ToFloat64(_CC_TBMONTH_SUM)
			temp.CC_HBMONTH_SUM = utils.ToFloat64(_CC_HBMONTH_SUM)
			

			list = append(list, temp)
		}
	}
	defer rows.Close()
	defer conn.Close()
	return list,nil
}

## sql1 was running well . 
[
  {
    "BrandCode": "SU",
    "BrandAlias": "SU",
    "ChannelCode": "Z015",
    "ChannelAlias": "",
    "CC_YEAR_SUM": 306703016.39,
    "CC_MONTH_SUM": 14295292.31,
    "CC_DAY_SUM": 655552,
    "CC_TBYEAR_SUM": 279843503.64,
    "CC_TBMONTH_SUM": 13457145.040000001,
    "CC_HBMONTH_SUM": 9654517.27
  },
.......
]
## sql2 give me those error infomations: 
my sql：SELECT TOP 10 BEHVO,BVTXT,KTOKD
                ,sum(CC_YEAR_SUM), sum(CC_MONTH_SUM), sum(CC_DAY_SUM)
                ,sum(CC_TBYEAR_SUM), sum(CC_TBMONTH_SUM), sum(CC_HBMONTH_SUM)
                from "_SYS_BIC"."MF_SALES.DAILYSALE/SALES_D_BEHVO" ('PLACEHOLDER' = ('$$IP_TO_DATE$$', '2017-10-10'))
                GROUP BY BEHVO,BVTXT,KTOKD
what happened：Invalid CESU-8

## Thank you very much for your help.
---------------------------------------------------------------------------------------------
### can you please check those code in go-hdb project?  connection errors sometimes.

hdb.protocol 2018/06/11 18:43:54 session.go:106: Connection read error local address 192.168.93.79:55780 remote address 192.168.2.34:30015: read tcp 192.168.93.79:55780->192.168.2.34:30015: i/o timeout

// Read implements the io.Reader interface.
func (c *sessionConn) Read(b []byte) (int, error) {
	//set timeout
	if err := c.conn.SetReadDeadline(time.Now().Add(c.timeout)); err != nil {
		return 0, err
	}
	n, err := c.conn.Read(b)
	if err != nil {
		errLogger.Printf("Connection read error local address %s remote address %s: %s", c.conn.LocalAddr(), c.conn.RemoteAddr(), err)
		c.isBad = true
		c.badError = err
		return n, driver.ErrBadConn
	}
	return n, nil
}

**Comment by d024441** [comment] 2018-06-17 14:40
Hi lulouis,
is it possible to provide access to the db or to provide the content of "_SYS_BIC"."MF_SALES.DAILYSALE/SALES_D_BEHVO" ?
Thanks and best regards

**Comment by lulouis** [comment] 2018-06-19 04:00
Hi Stefan Miller,
I'm asking my leader and our SAP BASIS，I‘ll feed back to you later.Would you mind giving me an email address？
Thank you very much.

**Comment by lulouis** [comment] 2018-06-19 05:08
@d024441

**Comment by d024441** [comment] 2018-06-19 06:52
Hi @lulouis,
>>> Would you mind giving me an email address？
I sent an email back to your email address maintained with your github account.
Best regards,
stefan

**Comment by d024441** [comment] 2018-06-21 17:56
Hi @lulouis,
thanks for providing access. The issue is clear now and will be fixed with the next patch version which is going to be available within the next days.
Thanks and best regards,
stefan

**Comment by d024441** [comment] 2018-06-23 17:46
SQL issue should be solved with #v0.12.1.
For the second issue (timeout) we need some more information - please open a new ticket if a reproducible example is available.
Best regards,
stefan

**Closed by d024441** 2018-06-23 17:46 UTC
Labels: bug

**Comment by lulouis** [comment] 2018-06-26 02:20
Dear Stefan Miller,

It’s work well now , the second issue was no longer appeared，maybe , you fixed those two bugs at onetime.

Have a nice day!


Thank you very much,
Louis

________________________________
发件人: Stefan Miller <notifications@github.com>
发送时间: Sunday, June 24, 2018 1:46:08 AM
收件人: SAP/go-hdb
抄送: 陆帅华; Mention
主题: Re: [SAP/go-hdb] go-hdb can not support for 'select something group by' ? (#22)


SQL issue should be solved with #v0.12.1.
For the second issue (timeout) we need some more information - please open a new ticket if a reproducible example is available.
Best regards,
stefan

―

**Comment by d024441** [comment] 2018-06-26 05:53
Hi Louis,
thanks a lot for confirming!
Have a nice day, too.
stefan
