### ISSUE TITLE
db.Query with NULL *LOB fields hangs

### ISSUE THREAD

**Issue by tc-turner** [SAP/go-hdb#18] opened 2018-01-24 21:24 UTC
In our HANA2 database we have a Column table with several NCLOB fields, some of them allow NULL data and when running a query with go-hdb `Query("SELECT POTENTIALLY_NULL FROM A_TABLE")`  the program hangs for close to 5 minutes before erroring out with the following

```
i/o timeout
2018/01/24 16:18:13 SQL HdbError 259 - invalid table name:  Could not find table/view A_TABLE in schema SYSTEM: line 1 col 36 (at pos 35)
``` 

I am explicitly setting the SCHEMA to the correct value and the included code works fine *if* the field I select is NOT NULL.

The JDBC driver handles this with no issues.  

I have ran WireShark and it seems that using the go-hdb driver the packets just stop flowing.

```go
package main

import (
	"database/sql"
	"fmt"
	"log"
	"net/url"

	_ "github.com/SAP/go-hdb/driver"
)

func getDbURL(host string, port int, username string, password string) string {

	dsn := &url.URL{
		Scheme: "hdb",
		User:   url.UserPassword(username, password),
		Host:   fmt.Sprintf("%s:%d", host, port),
	}
	return dsn.String()
}

func main() {
	db, err := sql.Open("hdb", getDbURL("my.hana.host", 30015, "SYSTEM", "SouperSecretPassword"))
	if err != nil {
		log.Fatal(err)
	}
	if err := db.Ping(); err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	_, err = db.Exec("SET SCHEMA MY_NOT_SYSTEM_SCHEMA")
	if err != nil {
		log.Fatal(err)
	}
	_, err = db.Query("SELECT POTENTIALLY_NULL FROM A_TABLE")
	if err != nil {
		log.Fatal(err)
	}
}
```

Go Version: `go version go1.9.3 darwin/amd64`
go-hdb Version: `const DriverVersion = "0.9.5"`

Thanks for writing the go-hdb library!!

**Comment by d024441** [comment] 2018-01-26 00:21
Ok - as the error clearly states, that the table cannot be found in schema SYSTEM:
- each db.<fct> takes a (most probably different) connection out of the connection pool
--> db.Exec("SET SCHEMA....") is most probably executed not in the same connection as the following db.Query(...)
- to guarantee the same connection, please use whether schema.tableName syntax in the query, a transaction or (golang > 1.9) a sql.Conn object

Please share the results after the change - thanks!

>>>Thanks for writing the go-hdb library!!
my pleasure

**Comment by d024441** [comment] 2018-02-04 22:06
Didn't hear back, so closing the issue

**Closed by d024441** 2018-02-04 22:06 UTC
Labels: question

**Comment by petar-iv** [comment] 2018-04-18 13:04
I also observe that the process hangs when trying to fetch a LOB with a value of `NULL` (with current state of master branch, go version: 1.10.1, HANA 2 SPS 2). Here is a scenario to reproduce:

```sql
create schema test;

create table test.table_1 (col clob not null);
insert into test.table_1 values('some-text');

create table test.table_2 (col clob);
insert into test.table_2 values(null);
```

```go
package main

import (
	"bytes"
	"database/sql"
	"fmt"

	"github.com/SAP/go-hdb/driver"
)

func main() {
	db, err := sql.Open("hdb", "hdb://<user>:<password>@<host>:<port>")
	if err != nil {
		panic(err)
	}
	defer db.Close()

	fetchLob(db, "non-null", "table_1")
	fetchLob(db, "null", "table_2")
}

func fetchLob(db *sql.DB, scenario string, tableName string) {
	fmt.Printf("Fetching %s LOB value ...\n", scenario)
	lob := new(driver.Lob)
	b := new(bytes.Buffer)
	lob.SetWriter(b)
	if err := db.QueryRow(fmt.Sprintf("select col from test.%s", tableName)).Scan(lob); err != nil {
		panic(err)
	}
	fmt.Printf("Fetched value: %v\n\n\n", b)
}
```

The output is:
```
Fetching non-null LOB value ...
Fetched value: some-text


Fetching null LOB value ...
```
There is no value from the second fetch because the process hangs.

Let me know if there is anything wrong in my coding or this is an issue in the library.

Many thanks

**Comment by d024441** [comment] 2018-04-22 16:03
should work with the newest release (v0.11.1) - please see new NullLob for scanning Lob null values

**Comment by petar-iv** [comment] 2018-04-26 13:45
Works as expected now, thanks a lot
